language: node_js
node_js:
  - '10'

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

cache:
    directories:
      - node_modules
  
script:
  - ng lint
  - ng test --watch=false
  - ng build --prod